opt_in_rules:
  - toggle_bool
  - modifier_order
  - yoda_condition
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - redundant_nil_coalescing
  - prefer_self_type_over_type_of_self
  - implicit_return
  - empty_string

disabled_rules:
  - trailing_comma
  - line_length
  - unused_closure_parameter
  - multiple_closures_with_trailing_closure
  - large_tuple
  - todo # This is silly - todos are there for a reason
#######################
## Rule configs
#######################

force_cast: warning
force_try: warning

nesting:
  type_level:
    warning: 4

type_name:
  allowed_symbols: "_"

identifier_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 40
    error: 50
  allowed_symbols: "_"
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
